import {
  Station,
  Expedition,
  Container,
  CargoItem,
  CargoMovement,
  InventoryItem,
  Personnel,
  PersonnelMovement,
  Asset,
  AssetMaintenance,
  EmergencyIncident,
  EmergencyAction,
  SystemAlert,
  AuditLog,
  ReportRecord
} from '../types';

export const SEED_STATIONS: Station[] = [
  {
    id: 'st-bharati',
    code: 'BHARATI-ANT-03',
    name: 'Bharati Station',
    region: 'Antarctic',
    coordinates: "69°24'S, 76°11'E",
    operationalStatus: 'Fully Operational',
    capacity: 47,
    currentPersonnel: 28,
    temperatureCelsius: -24.2,
    windSpeedKts: 28.5,
    communicationStatus: 'Nominal (Satcom Primary)',
    emergencyStatus: 'Normal',
    lastCommunication: new Date().toISOString(),
  },
  {
    id: 'st-maitri',
    code: 'MAITRI-ANT-02',
    name: 'Maitri Station',
    region: 'Antarctic',
    coordinates: "70°46'S, 11°44'E",
    operationalStatus: 'Wintering Over',
    capacity: 65,
    currentPersonnel: 25,
    temperatureCelsius: -31.4,
    windSpeedKts: 36.0,
    communicationStatus: 'Nominal (Satcom Primary)',
    emergencyStatus: 'Normal',
    lastCommunication: new Date().toISOString(),
  },
  {
    id: 'st-himadri',
    code: 'HIMADRI-ARC-01',
    name: 'Himadri Station',
    region: 'Arctic',
    coordinates: "78°55'N, 11°56'E",
    operationalStatus: 'Fully Operational',
    capacity: 20,
    currentPersonnel: 8,
    temperatureCelsius: -12.6,
    windSpeedKts: 18.0,
    communicationStatus: 'Nominal (Satcom Primary)',
    emergencyStatus: 'Normal',
    lastCommunication: new Date().toISOString(),
  }
];

export const SEED_EXPEDITIONS: Expedition[] = [
  {
    id: 'exp-isea-44',
    code: 'ISEA-44',
    name: '44th Indian Scientific Expedition to Antarctica',
    leaderName: 'Dr. Rajeshwari Nair',
    stationId: 'st-bharati',
    startDate: '2025-11-15',
    endDate: '2026-12-20',
    status: 'Active',
    budgetAllocated: 48500000,
    personnelCount: 53,
    cargoWeightKg: 142500,
    description: 'Comprehensive Southern Ocean climatology, ice-sheet drilling, geomagnetism & year-round wintering observations.',
    createdAt: '2025-10-01T08:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'exp-awe-2026',
    code: 'AWE-2026',
    name: 'Arctic Winter Science Expedition 2026',
    leaderName: 'Dr. Neha Kulkarni',
    stationId: 'st-himadri',
    startDate: '2026-03-01',
    endDate: '2026-10-30',
    status: 'Preparing',
    budgetAllocated: 19800000,
    personnelCount: 14,
    cargoWeightKg: 31000,
    description: 'Ny-Ålesund fjord ecosystem bio-optics and upper atmospheric lidar sounding during seasonal sea-ice transition.',
    createdAt: '2026-01-10T09:30:00Z',
    updatedAt: new Date().toISOString(),
  }
];

export const SEED_CONTAINERS: Container[] = [
  {
    id: 'cont-iso-01',
    code: 'CONT-ISO-40-01',
    type: '40ft Heavy Arctic Spec',
    tareWeightKg: 4200,
    maxGrossWeightKg: 30480,
    currentStationOrHub: 'Maitri Station Ice Apron',
    status: 'Staged at Station',
  },
  {
    id: 'cont-reefer-02',
    code: 'CONT-REEFER-02',
    type: 'Reefer (-25°C)',
    tareWeightKg: 4800,
    maxGrossWeightKg: 28000,
    currentStationOrHub: 'Cape Town Logistics Hub',
    status: 'Loading',
  },
  {
    id: 'cont-fuel-03',
    code: 'CONT-FUEL-ISO-03',
    type: 'Fuel ISO Tank',
    tareWeightKg: 3600,
    maxGrossWeightKg: 26000,
    currentStationOrHub: 'MV Vasiliy Golovnin (En Route Larsemann Hills)',
    status: 'In Transit',
  }
];

export const SEED_CARGO: CargoItem[] = [
  {
    id: 'crg-fuel-101',
    trackingNumber: 'CRG-2026-089',
    name: 'Polar Aviation & Turbine Fuel (ATF-50 Arctic drums)',
    category: 'Fuel',
    priority: 'Critical',
    status: 'In Transit',
    expeditionId: 'exp-isea-44',
    destinationStationId: 'st-bharati',
    containerId: 'cont-fuel-03',
    weightKg: 18500,
    volumeM3: 24.5,
    isHazmat: true,
    hazmatDetails: 'UN1863 Class 3 Flammable Liquid (Aviation Turbine Fuel - Low Freeze)',
    temperatureControlled: false,
    currentLocation: 'MV Vasiliy Golovnin (Lat 62°10S, Long 68°40E)',
    originHub: 'Cape Town Port Terminal 4',
    estimatedArrival: '2026-10-15',
    specialInstructions: 'Transfer via double-hulled manifold pipeline directly to Bharati East Fuel Farm.',
    isSeedDemo: true,
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'crg-food-102',
    trackingNumber: 'CRG-2026-092',
    name: 'Nutritional Wintering Rations & Dehydrated Provisions',
    category: 'Food',
    priority: 'High',
    status: 'Packed',
    expeditionId: 'exp-isea-44',
    destinationStationId: 'st-bharati',
    containerId: 'cont-reefer-02',
    weightKg: 8200,
    volumeM3: 16.0,
    isHazmat: false,
    temperatureControlled: true,
    requiredTempRange: '-18°C to -22°C',
    currentLocation: 'NCPOR Logistics Staging Warehouse, Goa',
    originHub: 'NCPOR Vasco da Gama, Goa',
    estimatedArrival: '2026-10-28',
    specialInstructions: 'Verify datalogger temperature curve prior to icebreak transfer.',
    isSeedDemo: true,
    createdAt: '2026-08-25T14:30:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'crg-med-103',
    trackingNumber: 'CRG-2026-104',
    name: 'Cold-Climate Trauma Surgical Packs & Blood Plasma Kit',
    category: 'Medicine',
    priority: 'Critical',
    status: 'Dispatched',
    expeditionId: 'exp-isea-44',
    destinationStationId: 'st-bharati',
    weightKg: 240,
    volumeM3: 1.2,
    isHazmat: true,
    hazmatDetails: 'UN3373 Biological Substance Category B & Dry Ice UN1845',
    temperatureControlled: true,
    requiredTempRange: '2°C to 8°C (Monitored)',
    currentLocation: 'Cape Town Air Cargo Bay C',
    originHub: 'All India Institute of Medical Sciences (AIIMS) New Delhi',
    estimatedArrival: '2026-10-05',
    receivingOfficer: 'Dr. Priya Sharma',
    isSeedDemo: true,
    createdAt: '2026-09-01T09:15:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'crg-spares-104',
    trackingNumber: 'CRG-2026-077',
    name: 'Cummins Generator Replacement Turbocharger & Injectors',
    category: 'Spare Parts',
    priority: 'High',
    status: 'Delayed',
    expeditionId: 'exp-isea-44',
    destinationStationId: 'st-maitri',
    weightKg: 680,
    volumeM3: 2.1,
    isHazmat: false,
    temperatureControlled: false,
    currentLocation: 'Durban Customs Bonded Warehouse (Weather delay)',
    originHub: 'Mumbai Port Trust',
    estimatedArrival: '2026-10-20',
    specialInstructions: 'Expedite via Basler BT-67 charter flight once weather window opens.',
    isSeedDemo: true,
    createdAt: '2026-08-12T11:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'crg-sci-105',
    trackingNumber: 'CRG-2026-118',
    name: 'Deep Ice-Core Electromechanical Drill Head & Fiber Sensor',
    category: 'Scientific Equipment',
    priority: 'Medium',
    status: 'At Station',
    expeditionId: 'exp-isea-44',
    destinationStationId: 'st-bharati',
    containerId: 'cont-iso-01',
    weightKg: 3400,
    volumeM3: 7.8,
    isHazmat: false,
    temperatureControlled: false,
    currentLocation: 'Bharati Staging Apron Bunker',
    originHub: 'NCPOR Goa',
    estimatedArrival: '2026-09-10',
    actualArrival: '2026-09-12',
    receivingOfficer: 'Dr. Rajeshwari Nair',
    isSeedDemo: true,
    createdAt: '2026-07-28T16:00:00Z',
    updatedAt: new Date().toISOString(),
  }
];

export const SEED_CARGO_MOVEMENTS: CargoMovement[] = [
  {
    id: 'mv-01',
    cargoId: 'crg-fuel-101',
    status: 'Packed',
    location: 'Cape Town Terminal 4',
    timestamp: '2026-08-22T08:00:00Z',
    officerName: 'Logistics Officer K. Menon',
    notes: 'Certified for Southern Ocean voyage.'
  },
  {
    id: 'mv-02',
    cargoId: 'crg-fuel-101',
    status: 'Dispatched',
    location: 'MV Vasiliy Golovnin Berth 2',
    timestamp: '2026-08-28T14:00:00Z',
    officerName: 'Capt. S. Joshi',
    notes: 'Stowed in forward hold with marine tie-downs.'
  },
  {
    id: 'mv-03',
    cargoId: 'crg-fuel-101',
    status: 'In Transit',
    location: 'Roaring Forties (Lat 48°S, Long 42°E)',
    timestamp: '2026-09-15T12:00:00Z',
    officerName: 'First Mate Alexey V.',
    notes: 'Vessel maintaining 12 knots heading south.'
  }
];

export const SEED_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-bh-fuel',
    sku: 'SKU-FUEL-ATF-01',
    name: 'Polar Grade Diesel / Fuel Stock',
    category: 'Fuel',
    stationId: 'st-bharati',
    quantity: 14200,
    unit: 'Liters',
    minimumThreshold: 12000,
    criticalThreshold: 6000,
    dailyConsumption: 380, // 14200 / 380 = 37.3 days remaining!
    lastResupplyDate: '2026-02-14',
    nextPlannedResupplyDate: '2026-11-05', // Resupply in ~39 days -> Gap of ~2 days! Risk!
    storageLocation: 'Bharati Fuel Farm Tank 1 & 2',
    isSeedDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'inv-bh-food',
    sku: 'SKU-FOOD-RAT-02',
    name: 'Lyophilized Long-Life Food Rations',
    category: 'Food',
    stationId: 'st-bharati',
    quantity: 1680,
    unit: 'Rations',
    minimumThreshold: 2200,
    criticalThreshold: 1000,
    dailyConsumption: 70, // 1680 / 70 = 24.0 days remaining!
    expiryDate: '2027-12-31',
    lastResupplyDate: '2026-02-14',
    nextPlannedResupplyDate: '2026-11-05', // Next resupply in 39 days -> CRITICAL SHORTAGE of 15 days!
    storageLocation: 'Main Galley Freeze Vault B',
    isSeedDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'inv-bh-water',
    sku: 'SKU-WTR-RO-03',
    name: 'Reverse Osmosis Desalination Filter Membranes',
    category: 'Water & Treatment',
    stationId: 'st-bharati',
    quantity: 16,
    unit: 'Units',
    minimumThreshold: 8,
    criticalThreshold: 4,
    dailyConsumption: 0.05, // 320 days
    lastResupplyDate: '2026-02-14',
    nextPlannedResupplyDate: '2026-11-05',
    storageLocation: 'Water Treatment Plant Shelf A',
    isSeedDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'inv-bh-med',
    sku: 'SKU-MED-TRM-04',
    name: 'Emergency Hypothermia & Frostbite Treatment Kits',
    category: 'Medicine',
    stationId: 'st-bharati',
    quantity: 42,
    unit: 'Kits',
    minimumThreshold: 30,
    criticalThreshold: 15,
    dailyConsumption: 0.2, // 210 days
    expiryDate: '2027-06-30',
    lastResupplyDate: '2026-02-14',
    nextPlannedResupplyDate: '2026-11-05',
    storageLocation: 'Medical Ward Emergency Locker',
    isSeedDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'inv-mt-fuel',
    sku: 'SKU-MT-FUEL-01',
    name: 'Maitri Polar Diesel (Generator Feed)',
    category: 'Fuel',
    stationId: 'st-maitri',
    quantity: 26500,
    unit: 'Liters',
    minimumThreshold: 15000,
    criticalThreshold: 8000,
    dailyConsumption: 410, // ~64.6 days
    lastResupplyDate: '2026-01-20',
    nextPlannedResupplyDate: '2026-11-20',
    storageLocation: 'Priyadarshini Lake Fuel Bund',
    isSeedDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'inv-mt-food',
    sku: 'SKU-MT-FOOD-02',
    name: 'Maitri Wintering High-Calorie Rations',
    category: 'Food',
    stationId: 'st-maitri',
    quantity: 3800,
    unit: 'Rations',
    minimumThreshold: 2000,
    criticalThreshold: 1000,
    dailyConsumption: 62.5, // ~60.8 days
    expiryDate: '2027-08-30',
    lastResupplyDate: '2026-01-20',
    nextPlannedResupplyDate: '2026-11-20',
    storageLocation: 'Maitri Kitchen Storage Container 3',
    isSeedDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'inv-hm-food',
    sku: 'SKU-HM-FOOD-01',
    name: 'Arctic Emergency Meal Packs (MRE)',
    category: 'Food',
    stationId: 'st-himadri',
    quantity: 850,
    unit: 'Rations',
    minimumThreshold: 300,
    criticalThreshold: 150,
    dailyConsumption: 20, // 42.5 days
    expiryDate: '2028-01-15',
    lastResupplyDate: '2026-06-01',
    nextPlannedResupplyDate: '2026-10-10',
    storageLocation: 'Himadri Station Cold Locker',
    isSeedDemo: true,
    updatedAt: new Date().toISOString(),
  }
];

export const SEED_PERSONNEL: Personnel[] = [
  {
    id: 'prs-01',
    badgeNumber: 'POL-IND-04401',
    name: 'Dr. Rajeshwari Nair',
    role: 'Station Commander',
    specialization: 'Glaciology & Ice Core Paleoclimatology',
    expeditionId: 'exp-isea-44',
    stationId: 'st-bharati',
    currentLocation: 'Bharati Station (Command Module)',
    status: 'At Station',
    bloodGroup: 'O+',
    emergencyContact: '+91-98201-99812 (Husband: Dr. K. Nair)',
    certifications: ['Polar Expedition Leadership Level 4', 'Advanced Wilderness First Responder', 'Sea Ice Navigation'],
    deployedDate: '2025-11-15',
    rotationEndDate: '2026-12-20',
    isSeedDemo: true,
    createdAt: '2025-10-01T08:00:00Z',
  },
  {
    id: 'prs-02',
    badgeNumber: 'POL-IND-04402',
    name: 'Er. Amitav Ghosh',
    role: 'Chief Station Engineer',
    specialization: 'High-Latitude Power Generation & HVAC',
    expeditionId: 'exp-isea-44',
    stationId: 'st-bharati',
    currentLocation: 'Bharati Station (Power Plant)',
    status: 'At Station',
    bloodGroup: 'B+',
    emergencyContact: '+91-94330-12845 (Brother: S. Ghosh)',
    certifications: ['Arctic Diesel Overhaul Specialist', 'High Voltage Switchgear Safety', 'PistenBully Field Repair'],
    deployedDate: '2025-11-15',
    rotationEndDate: '2026-12-20',
    isSeedDemo: true,
    createdAt: '2025-10-01T08:00:00Z',
  },
  {
    id: 'prs-03',
    badgeNumber: 'POL-IND-04403',
    name: 'Dr. Priya Sharma',
    role: 'Polar Medical Officer',
    specialization: 'Emergency Trauma & Cold Weather Medicine',
    expeditionId: 'exp-isea-44',
    stationId: 'st-bharati',
    currentLocation: 'Bharati Station (Medical Bay)',
    status: 'At Station',
    bloodGroup: 'AB+',
    emergencyContact: '+91-98110-44567 (Father: Col. R. Sharma)',
    certifications: ['Polar Advanced Life Support (PALS)', 'Tele-Surgical Anesthesia', 'Hypothermia Rewarming Protocol'],
    deployedDate: '2025-11-15',
    rotationEndDate: '2026-12-20',
    isSeedDemo: true,
    createdAt: '2025-10-01T08:00:00Z',
  },
  {
    id: 'prs-04',
    badgeNumber: 'POL-IND-04404',
    name: 'Capt. Vikram Singh',
    role: 'Logistics & Traverse Commander',
    specialization: 'Over-Snow Heavy Traverses & Crevasse Rescue',
    expeditionId: 'exp-isea-44',
    stationId: 'st-bharati',
    currentLocation: 'Field Camp Polar Plateau (70°S)',
    status: 'Field Camp',
    bloodGroup: 'A+',
    emergencyContact: '+91-99200-33411 (Spouse: A. Singh)',
    certifications: ['Master Heavy Snowcat Operator', 'Crevasse Rescue Instructor', 'Iridium Field Comms'],
    deployedDate: '2025-11-15',
    rotationEndDate: '2026-12-20',
    isSeedDemo: true,
    createdAt: '2025-10-01T08:00:00Z',
  },
  {
    id: 'prs-05',
    badgeNumber: 'POL-IND-04312',
    name: 'Dr. Sanjay Verma',
    role: 'Meteorologist & Geophysicist',
    specialization: 'Stratospheric Ozone & Geomagnetic Pulsations',
    expeditionId: 'exp-isea-44',
    stationId: 'st-maitri',
    currentLocation: 'Maitri Station (Atmospheric Lab)',
    status: 'At Station',
    bloodGroup: 'O-',
    emergencyContact: '+91-97422-55019 (Spouse: M. Verma)',
    certifications: ['Ozone Sonde Launch Certified', 'Cold Weather Survival'],
    deployedDate: '2025-11-15',
    rotationEndDate: '2026-12-20',
    isSeedDemo: true,
    createdAt: '2025-10-01T08:00:00Z',
  },
  {
    id: 'prs-06',
    badgeNumber: 'POL-IND-04501',
    name: 'Dr. Neha Kulkarni',
    role: 'Station Leader',
    specialization: 'Marine Biogeochemistry & Arctic Ecology',
    expeditionId: 'exp-awe-2026',
    stationId: 'st-himadri',
    currentLocation: 'Himadri Station (Ny-Ålesund)',
    status: 'At Station',
    bloodGroup: 'B-',
    emergencyContact: '+91-98670-11234 (Mother: S. Kulkarni)',
    certifications: ['Svalbard Polar Bear Safety Firearm Permit', 'Zodiac Inshore Boat Master'],
    deployedDate: '2026-03-01',
    rotationEndDate: '2026-10-30',
    isSeedDemo: true,
    createdAt: '2026-01-10T09:30:00Z',
  }
];

export const SEED_PERSONNEL_MOVEMENTS: PersonnelMovement[] = [
  {
    id: 'pm-01',
    personnelId: 'prs-04',
    fromLocation: 'Bharati Station',
    toLocation: 'Field Camp Polar Plateau (70°S)',
    transportMode: 'PistenBully Snowcat',
    timestamp: '2026-09-20T06:00:00Z',
    authorizedBy: 'Dr. Rajeshwari Nair',
    status: 'Completed'
  }
];

export const SEED_ASSETS: Asset[] = [
  {
    id: 'ast-gen-01',
    code: 'AST-GEN-01',
    name: 'Cummins QSK19 Arctic Diesel Generator #1 (Primary)',
    category: 'Power & Heating',
    serialNumber: 'CUM-ANT-99120-A',
    stationId: 'st-bharati',
    operationalStatus: 'Operational',
    operatingHours: 5420,
    criticality: 'Vital Life-Support',
    commissionDate: '2022-01-10',
    lastMaintenanceDate: '2026-08-10',
    nextScheduledMaintenance: '2026-10-10', // Due in ~13 days
    assignedTeam: 'Electrical & Power Engineering Team',
    sparePartsNotes: 'Requires fuel filter cartridge and injector timing check at 5,500 hrs.',
    isSeedDemo: true,
    createdAt: '2022-01-10T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ast-gen-02',
    code: 'AST-GEN-02',
    name: 'Cummins QSK19 Arctic Diesel Generator #2 (Secondary)',
    category: 'Power & Heating',
    serialNumber: 'CUM-ANT-99120-B',
    stationId: 'st-bharati',
    operationalStatus: 'Maintenance Due',
    operatingHours: 6180,
    criticality: 'Vital Life-Support',
    commissionDate: '2022-01-10',
    lastMaintenanceDate: '2026-07-02',
    nextScheduledMaintenance: '2026-09-25', // Overdue by 2 days!
    assignedTeam: 'Electrical & Power Engineering Team',
    sparePartsNotes: 'Oil filter replacement kit staged in workshop rack 4.',
    isSeedDemo: true,
    createdAt: '2022-01-10T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ast-veh-01',
    code: 'AST-VEH-01',
    name: 'PistenBully 300 Polar Heavy Tracked Snowcat',
    category: 'Vehicles & Heavy Mobile',
    serialNumber: 'PB-POL-300-881',
    stationId: 'st-bharati',
    operationalStatus: 'Operational',
    operatingHours: 1840,
    criticality: 'Primary Operational',
    commissionDate: '2021-12-05',
    lastMaintenanceDate: '2026-08-25',
    nextScheduledMaintenance: '2026-11-25',
    assignedTeam: 'Over-Snow Logistics Team',
    sparePartsNotes: 'Track tension hydraulic seals verified normal.',
    isSeedDemo: true,
    createdAt: '2021-12-05T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ast-veh-02',
    code: 'AST-VEH-02',
    name: 'Prinzoth Everest Heavy Traverse Tractor',
    category: 'Vehicles & Heavy Mobile',
    serialNumber: 'PRZ-EVR-4019',
    stationId: 'st-maitri',
    operationalStatus: 'Under Maintenance',
    operatingHours: 3200,
    criticality: 'Primary Operational',
    commissionDate: '2020-02-14',
    lastMaintenanceDate: '2026-09-18',
    nextScheduledMaintenance: '2026-10-01',
    assignedTeam: 'Maitri Heavy Transport Unit',
    sparePartsNotes: 'Awaiting replacement hydraulic hose assembly from cargo CRG-2026-077.',
    isSeedDemo: true,
    createdAt: '2020-02-14T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ast-life-01',
    code: 'AST-LSS-01',
    name: 'Central Heat Recovery & Desalination Circulator Unit',
    category: 'Life Support & Water',
    serialNumber: 'CHR-LSS-3301',
    stationId: 'st-bharati',
    operationalStatus: 'Operational',
    operatingHours: 8900,
    criticality: 'Vital Life-Support',
    commissionDate: '2022-01-15',
    lastMaintenanceDate: '2026-09-01',
    nextScheduledMaintenance: '2026-12-01',
    assignedTeam: 'Facility Life Support Engineers',
    sparePartsNotes: 'Secondary glycol circulation pump tested on standby.',
    isSeedDemo: true,
    createdAt: '2022-01-15T00:00:00Z',
    updatedAt: new Date().toISOString(),
  }
];

export const SEED_ASSET_MAINTENANCE: AssetMaintenance[] = [
  {
    id: 'maint-01',
    assetId: 'ast-gen-01',
    maintenanceType: 'Routine Scheduled',
    status: 'Completed',
    technicianName: 'Er. Amitav Ghosh',
    performedDate: '2026-08-10',
    operatingHoursAtService: 5200,
    findings: 'All six cylinders compression within 2% tolerance. Fuel filter and oil changed.',
    partsReplaced: 'Spin-on oil filters x2, Fuel water separator element',
    nextDueDate: '2026-10-10'
  },
  {
    id: 'maint-02',
    assetId: 'ast-veh-02',
    maintenanceType: 'Corrective Repair',
    status: 'In Progress',
    technicianName: 'Mechanic R. Tandon',
    performedDate: '2026-09-18',
    operatingHoursAtService: 3200,
    findings: 'Micro-fracture in secondary hydraulic boom line due to -35°C thermal shock.',
    partsReplaced: 'Pending arrival of Arctic rated high-pressure hose',
    nextDueDate: '2026-10-01'
  }
];

export const SEED_EMERGENCIES: EmergencyIncident[] = [
  {
    id: 'emg-001',
    incidentCode: 'EMG-2026-001',
    title: 'Secondary Generator Fuel Injector Seal Breach & Pressure Loss',
    type: 'Equipment Failure',
    stationId: 'st-bharati',
    locationDetails: 'Bharati Power Generation Annex - Bay 2',
    severity: 'Severe (Level 2)',
    status: 'Active',
    description: 'During scheduled load transfer, Generator #2 fuel rail experienced pressure loss with sub-zero gasket weepage. Generator switched to emergency lockout. Station currently operating solely on Generator #1.',
    reportedBy: 'Er. Amitav Ghosh (Chief Engineer)',
    reportedAt: '2026-09-26T18:40:00Z',
    affectedPersonnelIds: ['prs-02'],
    requiredResources: ['Torque Wrench 120Nm', 'Spare Viton High-Cold Seal Kit', 'Infrared Thermal Imaging Sensor', 'Fire Extinguisher Halon Standby'],
    commanderNotes: 'Station commander Dr. Nair notified. Non-essential science loads shedded by 15% to conserve Gen #1 margin.',
    isSeedDemo: true
  }
];

export const SEED_EMERGENCY_ACTIONS: EmergencyAction[] = [
  {
    id: 'ea-01',
    incidentId: 'emg-001',
    actionText: 'Isolate Generator #2 fuel supply valve and vent fuel rail manifold safely.',
    assignedTo: 'Er. Amitav Ghosh',
    status: 'Completed',
    timestamp: '2026-09-26T18:50:00Z',
    completedAt: '2026-09-26T19:05:00Z'
  },
  {
    id: 'ea-02',
    incidentId: 'emg-001',
    actionText: 'Inspect injector #4 and #5 seating seals using borescope and thermal camera.',
    assignedTo: 'Er. Amitav Ghosh & Tech R. Sen',
    status: 'In Progress',
    timestamp: '2026-09-26T19:15:00Z'
  },
  {
    id: 'ea-03',
    incidentId: 'emg-001',
    actionText: 'Implement secondary emergency heat trace cable around primary fuel feed line.',
    assignedTo: 'Facility Duty Crew',
    status: 'Pending',
    timestamp: '2026-09-26T19:30:00Z'
  }
];

export const SEED_ALERTS: SystemAlert[] = [
  {
    id: 'alt-01',
    type: 'inventory_critical',
    title: 'Critical Supply Risk: Food Rations (Bharati)',
    message: 'Food rations at Bharati Station are projected to reach critical reserve threshold in 24 days, 15 days before scheduled resupply on 2026-11-05.',
    severity: 'critical',
    timestamp: new Date().toISOString(),
    entityType: 'inventory',
    entityId: 'inv-bh-food',
    read: false,
  },
  {
    id: 'alt-02',
    type: 'emergency_active',
    title: 'Active Level-2 Emergency at Bharati Station',
    message: 'Generator #2 fuel line breach active. Station operating on single power generator.',
    severity: 'critical',
    timestamp: '2026-09-26T18:40:00Z',
    entityType: 'emergency',
    entityId: 'emg-001',
    read: false,
  },
  {
    id: 'alt-03',
    type: 'asset_overdue',
    title: 'Maintenance Overdue: Generator #2',
    message: 'Scheduled 500-hr polar service for Generator #2 is 2 days overdue.',
    severity: 'warning',
    timestamp: '2026-09-25T08:00:00Z',
    entityType: 'asset',
    entityId: 'ast-gen-02',
    read: false,
  },
  {
    id: 'alt-04',
    type: 'cargo_delayed',
    title: 'Cargo Delayed: Generator Spare Parts',
    message: 'Consignment CRG-2026-077 delayed at Durban hub due to Southern Ocean gale warning.',
    severity: 'warning',
    timestamp: '2026-09-24T12:00:00Z',
    entityType: 'cargo',
    entityId: 'crg-spares-104',
    read: true,
  }
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-01',
    userName: 'Dr. Rajeshwari Nair',
    action: 'Emergency Created',
    entity: 'Emergency',
    entityId: 'emg-001',
    newValue: 'Secondary Generator Fuel Injector Seal Breach (Level 2)',
    timestamp: '2026-09-26T18:40:00Z'
  },
  {
    id: 'aud-02',
    userName: 'Capt. Vikram Singh',
    action: 'Cargo Status Changed',
    entity: 'Cargo',
    entityId: 'crg-fuel-101',
    previousValue: 'Dispatched',
    newValue: 'In Transit',
    timestamp: '2026-09-15T12:00:00Z'
  },
  {
    id: 'aud-03',
    userName: 'Er. Amitav Ghosh',
    action: 'Asset Maintenance Recorded',
    entity: 'Asset',
    entityId: 'ast-gen-01',
    newValue: 'Routine 5,000-hr Polar Overhaul Completed',
    timestamp: '2026-08-10T14:30:00Z'
  }
];

export const SEED_REPORTS: ReportRecord[] = [
  {
    id: 'rep-01',
    reportCode: 'REP-2026-Q3-01',
    title: 'Bharati Station Q3 Operational Readiness & Logistics Review',
    category: 'Expedition Summary',
    generatedBy: 'AI Systems Engine & Dr. Rajeshwari Nair',
    generatedAt: '2026-09-20T10:00:00Z',
    stationId: 'st-bharati',
    aiGeneratedSummary: true,
    summaryHighlights: [
      'Fuel reserve stands at 14,200 L with 37.3 days projected autonomy.',
      'Food supply presents urgent 15-day gap prior to MV Vasiliy Golovnin docking.',
      'Generator redundancy is presently compromised following fuel line issue on Gen #2.',
      'All 28 wintering personnel are accounted for with medical clearance intact.'
    ],
    contentMarkdown: `## Executive Summary
Bharati Station operational posture remains steady across life-support systems, however immediate attention is required for food resupply scheduling and secondary power generation maintenance.

### Key Operational Indicators
- **Personnel Deployed:** 28 on-site, 1 field camp
- **Average Temperature:** -24.2°C | Winds: 28.5 kts
- **Power Generation:** 175 kW avg load on Primary Gen #1
- **Next Resupply Window:** 2026-11-05 (estimated)`
  }
];
